Reverse sort stats by Scala/SJS/SN/SBT/Mill version on frontpage
scalacenter/scaladex pull request #1153
Opened 2023-01-30 17:31 UTC by keynmol

Closes #1151

2023-02-02 09:40 UTC, julienrf requested changes
Thank you @keynmol for helping with this!

I think what you propose works, but I wonder if we should fix the issue upstream, by changing the definition of the `Ordering[SemanticVersion]` to always show higher versions first (which is the natural ordering for versions). That will probably have impacts in a couple of other places, though… Would you be interested in trying that approach?

2023-02-02 09:49 UTC, keynmol commented
> always show higher versions first (which is the natural ordering for versions).

Hmm I'm not sure I fully agree whether it's "natural", i.e. would you expect `1.2.0 > 3.2.0`? 

Alternatively, I can define a `LatestFirst` explicit ordering, and move the ordering out of the templates and into the code that calls them.

I've been interpreting ordering as numeric, and from the semver docs: 
<img width="693" alt="image" src="https://user-images.githubusercontent.com/1052965/216290827-2b3edbc2-35d4-46dc-be57-e7b1338abd1d.png">

obviously they `<` is an overloaded operator :)

2023-02-02 10:11 UTC, julienrf commented
OK, you are right that what I said would be confusing with `>`… Let’s keep the `Ordering[SemanticVersion]` as it is.

2023-02-02 10:14 UTC, julienrf commented on modules/server/src/main/scala/scaladex/server/route/FrontPage.scala
> +      val millVersions = platforms.collect { case (v: MillPlugin, c) => (v, c) }.sortBy(_._1.version).reverse
It seems `languages` and `platforms` are created on lines 38 and 39, from the result of calls to `SearchEngine#countByLanguages()` and `SearchEngine#countByPlatforms()`, and those methods return the result in the order that we want but we reverse them at lines 38 and 39. Should we just drop the `.map(_.sorted)` from those lines?

2023-02-13 08:47 UTC, julienrf approved these changes
Thank you @keynmol for your help! I agree with your analysis.

2023-02-13 08:57 UTC, merged

2023-02-13 11:07 UTC, julienrf commented
This is now live on https://index.scala-lang.org!